In [59]:
pip install --upgrade scipy

Requirement already satisfied: scipy in c:\users\tanvi\anaconda3\lib\site-packages (1.16.3)
Collecting scipy
  Downloading scipy-1.17.0-cp313-cp313-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: numpy<2.7,>=1.26.4 in c:\users\tanvi\anaconda3\lib\site-packages (from scipy) (2.3.5)
Downloading scipy-1.17.0-cp313-cp313-win_amd64.whl (36.3 MB)
   ---------------------------------------- 0.0/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.3 MB ? eta -:--:--
    --------------------------------------- 0.5/36.3 MB 71.0 kB/s eta 0:08:24
    --------------------------------------- 0.5/36.3 MB 71.0 kB/s eta 0:08:24
    --------------------------------------- 0.5/36.3 MB 71.0 kB/s eta 0:08:24
    --------------------------------------- 0.8/36.3 MB 119.2 kB/s eta 0:04:58
    --------------------------------------- 0.8/36.3 MB 119.2 kB/s eta 0:04:58
    --------------------------------------- 0.8/36.3 MB 119.2 kB/s eta 0:04:58
    --------------------------------------- 0.8/36.3 MB 119.2 kB/s eta 0:04:58
    --------------------------------------- 0.8/36.3 MB 119.2 kB/s eta 0:04:58
    --------------------------------------- 0.8/36.3 MB 119.2 kB/s eta 0:04:58
    --------------------------------------- 0.8/36.3 MB 119.2 kB/s eta 0:04:58
    --------------------------------------- 0.8/36.3 MB 119.2 kB/s eta 0:04:58
    --------------------------------------- 0.8/36.3 MB 119.2 kB/s eta 0:04:58
    --------------------------------------- 0.8/36.3 MB 119.2 kB/s eta 0:04:58
    --------------------------------------- 0.8/36.3 MB 119.2 kB/s eta 0:04:58
    --------------------------------------- 0.8/36.3 MB 119.2 kB/s eta 0:04:58
    --------------------------------------- 0.8/36.3 MB 119.2 kB/s eta 0:04:58
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.0/36.3 MB 111.0 kB/s eta 0:05:18
   - -------------------------------------- 1.3/36.3 MB 69.0 kB/s eta 0:08:28
   - -------------------------------------- 1.3/36.3 MB 69.0 kB/s eta 0:08:28
   - -------------------------------------- 1.3/36.3 MB 69.0 kB/s eta 0:08:28
   - -------------------------------------- 1.3/36.3 MB 69.0 kB/s eta 0:08:28
   - -------------------------------------- 1.3/36.3 MB 69.0 kB/s eta 0:08:28
   - -------------------------------------- 1.3/36.3 MB 69.0 kB/s eta 0:08:28
   - -------------------------------------- 1.3/36.3 MB 69.0 kB/s eta 0:08:28
   - -------------------------------------- 1.3/36.3 MB 69.0 kB/s eta 0:08:28
   - -------------------------------------- 1.3/36.3 MB 69.0 kB/s eta 0:08:28
   - -------------------------------------- 1.3/36.3 MB 69.0 kB/s eta 0:08:28
   - -------------------------------------- 1.3/36.3 MB 69.0 kB/s eta 0:08:28
   - -------------------------------------- 1.3/36.3 MB 69.0 kB/s eta 0:08:28
   - -------------------------------------- 1.3/36.3 MB 69.0 kB/s eta 0:08:28
   - -------------------------------------- 1.6/36.3 MB 73.0 kB/s eta 0:07:56
   -- ------------------------------------- 1.8/36.3 MB 86.5 kB/s eta 0:06:39
   -- ------------------------------------- 2.1/36.3 MB 99.7 kB/s eta 0:05:43
   -- ------------------------------------- 2.6/36.3 MB 126.5 kB/s eta 0:04:27
   --- ------------------------------------ 3.1/36.3 MB 153.1 kB/s eta 0:03:37
   --- ------------------------------------ 3.1/36.3 MB 153.1 kB/s eta 0:03:37
   --- ------------------------------------ 3.4/36.3 MB 164.2 kB/s eta 0:03:21
   --- ------------------------------------ 3.4/36.3 MB 164.2 kB/s eta 0:03:21
   --- ------------------------------------ 3.4/36.3 MB 164.2 kB/s eta 0:03:21
   ---- ----------------------------------- 3.7/36.3 MB 171.3 kB/s eta 0:03:11
   ---- ----------------------------------- 3.7/36.3 MB 171.3 kB/s eta 0:03:11
   ---- ----------------------------------- 3.7/36.3 MB 171.3 kB/s eta 0:03:11
   ---- ----------------------------------- 3.9/36.3 MB 178.7 kB/s eta 0:03:02
   ---- ----------------------------------- 3.9/36.3 MB 178.7 kB/s eta 0:03:02
   ---- ----------------------------------- 3.9/36.3 MB 178.7 kB/s eta 0:03:02
   ---- ----------------------------------- 3.9/36.3 MB 178.7 kB/s eta 0:03:02
   ---- ----------------------------------- 4.2/36.3 MB 183.7 kB/s eta 0:02:55
   ---- ----------------------------------- 4.2/36.3 MB 183.7 kB/s eta 0:02:55
   ---- ----------------------------------- 4.2/36.3 MB 183.7 kB/s eta 0:02:55
   ---- ----------------------------------- 4.2/36.3 MB 183.7 kB/s eta 0:02:55
   ---- ----------------------------------- 4.5/36.3 MB 188.7 kB/s eta 0:02:49
   ---- ----------------------------------- 4.5/36.3 MB 188.7 kB/s eta 0:02:49
   ---- ----------------------------------- 4.5/36.3 MB 188.7 kB/s eta 0:02:49
   ----- ---------------------------------- 4.7/36.3 MB 195.9 kB/s eta 0:02:42
   ----- ---------------------------------- 4.7/36.3 MB 195.9 kB/s eta 0:02:42
   ----- ---------------------------------- 4.7/36.3 MB 195.9 kB/s eta 0:02:42
   ----- ---------------------------------- 4.7/36.3 MB 195.9 kB/s eta 0:02:42
   ----- ---------------------------------- 5.0/36.3 MB 198.8 kB/s eta 0:02:38
   ----- ---------------------------------- 5.0/36.3 MB 198.8 kB/s eta 0:02:38
   ----- ---------------------------------- 5.0/36.3 MB 198.8 kB/s eta 0:02:38
   ----- ---------------------------------- 5.0/36.3 MB 198.8 kB/s eta 0:02:38
   ----- ---------------------------------- 5.0/36.3 MB 198.8 kB/s eta 0:02:38
   ----- ---------------------------------- 5.0/36.3 MB 198.8 kB/s eta 0:02:38
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
   ----- ---------------------------------- 5.2/36.3 MB 199.7 kB/s eta 0:02:36
Resuming download scipy-1.17.0-cp313-cp313-win_amd64.whl (5.2 MB/36.3 MB)
   ----- ---------------------------------- 5.2/36.3 MB ? eta -:--:--
   ------ --------------------------------- 5.5/36.3 MB 1.4 MB/s eta 0:00:22
   ------ --------------------------------- 5.5/36.3 MB 1.4 MB/s eta 0:00:22
   ------ --------------------------------- 5.5/36.3 MB 1.4 MB/s eta 0:00:22
   ------ --------------------------------- 5.5/36.3 MB 1.4 MB/s eta 0:00:22
   ------ --------------------------------- 5.5/36.3 MB 1.4 MB/s eta 0:00:22
   ------ --------------------------------- 5.5/36.3 MB 1.4 MB/s eta 0:00:22
   ------ --------------------------------- 5.5/36.3 MB 1.4 MB/s eta 0:00:22
   ------ --------------------------------- 5.5/36.3 MB 1.4 MB/s eta 0:00:22
   ------ --------------------------------- 5.8/36.3 MB 293.5 kB/s eta 0:01:44
   ------ --------------------------------- 5.8/36.3 MB 293.5 kB/s eta 0:01:44
   ------ --------------------------------- 5.8/36.3 MB 293.5 kB/s eta 0:01:44
   ------ --------------------------------- 5.8/36.3 MB 293.5 kB/s eta 0:01:44
   ------ --------------------------------- 5.8/36.3 MB 293.5 kB/s eta 0:01:44
   ------ --------------------------------- 5.8/36.3 MB 293.5 kB/s eta 0:01:44
   ------ --------------------------------- 5.8/36.3 MB 293.5 kB/s eta 0:01:44
   ------ --------------------------------- 5.8/36.3 MB 293.5 kB/s eta 0:01:44
   ------ --------------------------------- 5.8/36.3 MB 293.5 kB/s eta 0:01:44
   ------ --------------------------------- 5.8/36.3 MB 293.5 kB/s eta 0:01:44
   ------ --------------------------------- 5.8/36.3 MB 293.5 kB/s eta 0:01:44
   ------ --------------------------------- 5.8/36.3 MB 293.5 kB/s eta 0:01:44
   ------ --------------------------------- 5.8/36.3 MB 293.5 kB/s eta 0:01:44
   ------ --------------------------------- 5.8/36.3 MB 293.5 kB/s eta 0:01:44
   ------ --------------------------------- 5.8/36.3 MB 293.5 kB/s eta 0:01:44
   ------ --------------------------------- 5.8/36.3 MB 293.5 kB/s eta 0:01:44
   ------ --------------------------------- 5.8/36.3 MB 293.5 kB/s eta 0:01:44
   ------ --------------------------------- 5.8/36.3 MB 293.5 kB/s eta 0:01:44
   ------ --------------------------------- 5.8/36.3 MB 293.5 kB/s eta 0:01:44
   ------ --------------------------------- 5.8/36.3 MB 293.5 kB/s eta 0:01:44
   ------ --------------------------------- 5.8/36.3 MB 293.5 kB/s eta 0:01:44
   ------ --------------------------------- 5.8/36.3 MB 293.5 kB/s eta 0:01:44
   ------ --------------------------------- 5.8/36.3 MB 293.5 kB/s eta 0:01:44
   ------ --------------------------------- 5.8/36.3 MB 293.5 kB/s eta 0:01:44
   ------ --------------------------------- 5.8/36.3 MB 293.5 kB/s eta 0:01:44
   ------ --------------------------------- 5.8/36.3 MB 293.5 kB/s eta 0:01:44
   ------ --------------------------------- 5.8/36.3 MB 293.5 kB/s eta 0:01:44
   ------ --------------------------------- 5.8/36.3 MB 293.5 kB/s eta 0:01:44
   ------ --------------------------------- 5.8/36.3 MB 293.5 kB/s eta 0:01:44
   ------ --------------------------------- 5.8/36.3 MB 293.5 kB/s eta 0:01:44
   ------ --------------------------------- 5.8/36.3 MB 293.5 kB/s eta 0:01:44
   ------ --------------------------------- 5.8/36.3 MB 293.5 kB/s eta 0:01:44
   ------ --------------------------------- 5.8/36.3 MB 293.5 kB/s eta 0:01:44
   ------ --------------------------------- 5.8/36.3 MB 293.5 kB/s eta 0:01:44

WARNING: Connection timed out while downloading.
WARNING: Attempting to resume incomplete download (5.2 MB/36.3 MB, attempt 1)

In [9]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.feature_extraction.text import CountVectorizer 
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

In [10]:
data= pd.read_csv('dataset.csv')

In [11]:
data.head()

                                                Text  language
0  klement gottwaldi surnukeha palsameeriti ning ...  Estonian
1  sebes joseph pereira thomas  på eng the jesuit...   Swedish
2  ถนนเจริญกรุง อักษรโรมัน thanon charoen krung เ...      Thai
3  விசாகப்பட்டினம் தமிழ்ச்சங்கத்தை இந்துப் பத்திர...     Tamil
4  de spons behoort tot het geslacht haliclona en...     Dutch

In [12]:
data.shape

(22000, 2)

In [13]:
data

                                                    Text  language
0      klement gottwaldi surnukeha palsameeriti ning ...  Estonian
1      sebes joseph pereira thomas  på eng the jesuit...   Swedish
2      ถนนเจริญกรุง อักษรโรมัน thanon charoen krung เ...      Thai
3      விசாகப்பட்டினம் தமிழ்ச்சங்கத்தை இந்துப் பத்திர...     Tamil
4      de spons behoort tot het geslacht haliclona en...     Dutch
...                                                  ...       ...
21995  hors du terrain les années  et  sont des année...    French
21996  ใน พศ  หลักจากที่เสด็จประพาสแหลมมลายู ชวา อินเ...      Thai
21997  con motivo de la celebración del septuagésimoq...   Spanish
21998  年月，當時還只有歲的她在美國出道，以mai-k名義推出首張英文《baby i like》，由...   Chinese
21999   aprilie sonda spațială messenger a nasa și-a ...  Romanian

[22000 rows x 2 columns]

In [14]:
data.isnull().sum()

Text        0
language    0
dtype: int64

In [15]:
data['language'].value_counts()

language
Estonian      1000
Swedish       1000
English       1000
Russian       1000
Romanian      1000
Persian       1000
Pushto        1000
Spanish       1000
Hindi         1000
Korean        1000
Chinese       1000
French        1000
Portugese     1000
Indonesian    1000
Urdu          1000
Latin         1000
Turkish       1000
Japanese      1000
Dutch         1000
Tamil         1000
Thai          1000
Arabic        1000
Name: count, dtype: int64

In [16]:
data.dtypes

Text        object
language    object
dtype: object

In [17]:
x = np.array(data['Text'])
y = np.array(data['language'])

In [18]:
cv = CountVectorizer()
X = cv.fit_transform(x)

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state=42)

In [20]:
X_train

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 613529 stored elements and shape (14740, 277720)>

In [24]:
model = MultinomialNB()

In [25]:
model.fit(X_train,y_train)

MultinomialNB()

In [29]:
model.score(X_test,y_test)

0.953168044077135

In [33]:
user = input("Enter a test")
data = cv.transform([user]).toarray()
output = model.predict(data)
print (output)

Enter a test परून पाहण्‍यासाठी, खालील आपली भाषा आणि इनपुट साधन निवडा आणि टाइप करण्‍यास सुरूवात करा. हे सॉफ्टवेअर डाउनलोड करण्यासाठी आप

['Hindi']